SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ASSET_DTL](
	[AS_ID] [int] IDENTITY(1,1) NOT NULL,
	[AS_CODE] [varchar](20) NOT NULL,
	[AS_GRP] [varchar](20) NOT NULL,
	[AS_NAME] [varchar](max) NOT NULL,
	[AS_NP] [numeric](18, 2) NULL,
	[AS_INDATE] [datetime] NULL,
	[AS_USE] [numeric](5, 2) NULL,
	[AS_PPB] [numeric](18, 2) NULL,
	[AS_TPT] [numeric](5, 2) NULL,
	[AS_STATUS] [char](1) NULL,
	[AS_LASTUPDATED_DT] [datetime] NULL,
	[AS_VOUCHER] [varchar](30) NULL,
	[AS_DIV] [int] NULL,
 CONSTRAINT [PK_ASSET_DTL] PRIMARY KEY CLUSTERED 
(
	[AS_CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ASSET_DTL] ADD  CONSTRAINT [DF_ASSET_DTL_AS_STATUS]  DEFAULT ('O') FOR [AS_STATUS]
GO
