SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ASSET_DIV](
	[DIV_ID] [int] IDENTITY(1,1) NOT NULL,
	[DIV_DESC] [varchar](max) NOT NULL,
	[DIV_INDATE] [datetime] NOT NULL,
	[DIV_STATUS] [varchar](1) NOT NULL,
 CONSTRAINT [PK_ASSET_DIV] PRIMARY KEY CLUSTERED 
(
	[DIV_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ASSET_DIV] ADD  CONSTRAINT [DF_ASSET_DIV_DIV_STATUS]  DEFAULT ('O') FOR [DIV_STATUS]
GO