SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ASSET_GRP](
	[GRP_ID] [int] IDENTITY(1,1) NOT NULL,
	[GRP_CODE] [varchar](20) NOT NULL,
	[GRP_DESC] [varchar](max) NOT NULL,
	[GRP_INDATE] [datetime] NOT NULL,
	[GRP_STATUS] [varchar](1) NOT NULL,
 CONSTRAINT [PK_ASSET_GRP] PRIMARY KEY CLUSTERED 
(
	[GRP_CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ASSET_GRP] ADD  CONSTRAINT [DF_ASSET_GRP_GRP_STATUS]  DEFAULT ('O') FOR [GRP_STATUS]
GO